workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      groups:
        - ios_signing_credentials

    scripts:
      - name: Initialize keychain
        script: keychain initialize

      - name: Clean Pods and reinstall
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod repo update
          pod install
          cd ..

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.admin.churppyAdmin" \
          --platform IOS \
          --type IOS_APP_STORE \
          --create

      - name: Add signing certificate to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles

      # ✅ Let Codemagic/Xcode handle signing automatically
      - name: Build signed IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "Runner" \
            --automatic-signing \
            --team-id 7H4229UD7R

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
