workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      groups:
        - ios_signing_credentials

    scripts:
      - name: Set up keychain for code signing
        script: keychain initialize

      - name: Clean Pods and reinstall
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Fetch signing files (automatic)
        script: |
          app-store-connect fetch-signing-files "com.admin.churppyAdmin" \
          --platform IOS \
          --type IOS_APP_STORE \
          --create

      - name: Add signing certificate to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles automatically
        script: |
          xcode-project use-profiles --project "ios/Runner.xcodeproj"

      # ✅ Automatic signing build (recommended)
      - name: Build IPA (Automatic Signing)
        script: |
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "Runner" \
            --allowProvisioningUpdates \
            --archive-xcargs "DEVELOPMENT_TEAM=7H4229UD7R CODE_SIGN_STYLE=Automatic"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
