workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - ios_signing_credentials

    scripts:
      - name: Initialize keychain
        script: keychain initialize

      - name: Clean Pods and reinstall
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod repo update
          pod install
          cd ..

      - name: Fetch signing files via API
        script: |
          app-store-connect fetch-signing-files "com.admin.churppyAdmin" \
          --platform IOS \
          --type IOS_APP_STORE \
          --create

      - name: Build signed IPA (automatic from API)
        script: |
          app-store-connect build-ipa \
            --type IOS_APP_STORE \
            --bundle-id "com.admin.churppyAdmin" \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "Runner"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
